version: '3.8'

services:
  # Mock SAP Connector (replaces real SAP Connector for local development)
  mock-sap:
    build:
      context: ./mock-sap
      dockerfile: Dockerfile
    container_name: mock-sap
    depends_on:
      postgres:
        condition: service_started
        required: true
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/ready || exit 1"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    ports:
      - "8000:8000"

  # Validation Engine
  validation-engine:
    build:
      context: ./validation-engine
      dockerfile: Dockerfile
    container_name: validation-engine
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_started
        required: true
      mock-sap:
        condition: service_started
        required: true
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RULES_PATH=/app/config/rules
      - CORS_ORIGINS=${CORS_ORIGINS}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8001/ready || exit 1"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - ./validation-engine:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
    ports:
      - "8001:8001"
    secrets:
      - source: db_password
        target: /run/secrets/db_password
        mode: 0444

  # Logging & Reporting Service
  logging-service:
    build: ./logging-service
    container_name: logging-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - AI_DB_HOST=${AI_DB_HOST:-${DB_HOST}}
      - AI_DB_NAME=${AI_DB_NAME:-${DB_NAME}}
      - AI_DB_USER=${AI_DB_USER:-ai_agent_user}
      - AI_DB_PASSWORD_FILE=/run/secrets/ai_db_password
      - FLASK_ENV=production
      - SECRET_KEY_FILE=/run/secrets/flask_secret_key
      - CORS_ORIGINS=${CORS_ORIGINS}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - DEFAULT_RATE_LIMIT=${DEFAULT_RATE_LIMIT:-60/minute}
      - AUDIT_LOGGING_ENABLED=${AUDIT_LOGGING_ENABLED:-true}
      - SECURITY_MONITORING_ENABLED=${SECURITY_MONITORING_ENABLED:-true}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOAD_BALANCER_ENABLED=${LOAD_BALANCER_ENABLED:-true}
      - SESSION_LIFETIME_HOURS=${SESSION_LIFETIME_HOURS:-8}
      - SESSION_COOKIE_SAMESITE=${SESSION_COOKIE_SAMESITE:-Lax}
      - AI_AGENTS_ENABLED=${AI_AGENTS_ENABLED:-true}
    volumes:
      - ./logging-service:/app
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    secrets:
      - db_password
      - flask_secret_key
      - ai_db_password
    networks:
      - sap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Orchestrator (Airflow)
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    depends_on:
      postgres:
        condition: service_started
        required: true
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY:-your-fernet-key-here-change-in-production}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER:-sap_user}:${DB_PASSWORD:-your_db_password}@postgres:5432/${DB_NAME:-sap_data_quality}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY:-your-secret-key-here-change-in-production}
      - SAP_CLIENT=${SAP_CLIENT:-100}
      - SAP_HOST=${SAP_HOST:-mock-sap}
      - SAP_PASSWORD=${SAP_PASSWORD:-your_sap_password}
      - SAP_USERNAME=${SAP_USERNAME:-sap_user}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
    ports:
      - "8081:8080"

  # PostgreSQL Database with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    container_name: sap-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-sap_user} -d ${DB_NAME:-sap_data_quality}"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./pgvector-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    secrets:
      - db_password

  # pgAdmin for Database Administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sap-pgadmin
    depends_on:
      postgres:
        condition: service_started
        required: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@sap-data-quality.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"

  # Redis for Airflow
  redis:
    image: redis:7-alpine
    container_name: sap-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      interval: 30s
      retries: 3
    networks:
      - sap-network
    restart: unless-stopped

  # Prometheus for Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: sap-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: sap-grafana
    depends_on:
      prometheus:
        condition: service_started
        required: true
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    networks:
      - sap-network
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"

networks:
  sap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:
  prometheus_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  flask_secret_key:
    file: ./secrets/flask_secret_key.txt
  ai_db_password:
    file: ./secrets/ai_db_password.txt

# TODO: Verify secrets exist in ./secrets. For Kubernetes, replace with native secrets.