name: CI

on:
  push:
    branches: [ main, ai-agents-integration ]
  pull_request:
    branches: [ main, ai-agents-integration ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tests
        run: |
          pytest -q

